# Generated by Django 4.2.4 on 2023-09-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_booking_comment_remove_booking_guest_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='reservation_date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reservation_slot',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_item_description',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='TempName', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.SmallIntegerField(default=2, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.SmallIntegerField(default=5, max_length=5),
            preserve_default=False,
        ),
    ]
